### PR TITLE
CODE RUB:Code Update on StudentService validation 

### PR DESCRIPTION
**Pull request by Noahmahi2019**

### CODE REVIEW

**Review by ShriHumrudha — CHANGES_REQUESTED** [review]
Got conflicts

**Comment by Noahmahi2019** [comment]
> Got conflicts
Here  is the right one.
bo63dbc

**Comment by ShriHumrudha** [comment]
@Noahmahi2019 I did not understand the reply.

**Comment by ShriHumrudha** [comment]
Beyond the 3 day window.

**Pull request closed without merging**
