### PR TITLE
ExamAttachment Service Retrieve by Id

### PR DESCRIPTION
**Pull request by viralpandya**

### CODE REVIEW

**Comment by hassanhabib** [comment]
@viralpandya please address conflicts

**Comment by viralpandya** [comment]
Resolved

**Comment by viralpandya** [comment]
> @viralpandya please address conflicts

**Comment by hassanhabib** [comment]
@viralpandya you've got some more conflicts, please address.

**Comment by viralpandya** [comment]
> @viralpandya you've got some more conflicts, please address.

Resolved

**Pull request merged**
