### PR TITLE
CODE RUB: Course Status Enum Validation

### LINKED ISSUE #503: CODE RUB: Course Status Enum Validation
Reference: https://github.com/hassanhabib/OtripleS/pull/499

### PR DESCRIPTION
**Pull request by arafat-pro**
Closes #503

### CODE REVIEW

**Comment by hassanhabib** [comment]
@arafat-pro tests are failing for this change. please correct the issues and try again.

**Comment by arafat-pro** [comment]
> @arafat-pro tests are failing for this change. please correct the issues and try again.

@hassanhabib I tried to dig into the issue of test failures though I am not enough knowledgable to debug with the failed tests.
I tried my forked repo before the last PR branching and found the test failures there.
I downloaded this master repo to local and I found that tests are also failing in the current repo where my PR was not merged.
Lastly, I am looking for your guidance!

**Comment by ShriHumrudha** [comment]
> > @arafat-pro tests are failing for this change. please correct the issues and try again.
> 
> @hassanhabib I tried to dig into the issue of test failures though I am not enough knowledgable to debug with the failed tests. I tried my forked repo before the last PR branching and found the test failures there. I downloaded this master repo to local and I found that tests are also failing in the current repo where my PR was not merged. Lastly, I am looking for your guidance!

Hi @arafat-pro , You are growing as a strong developer. Just another tip for you to resolve this issue.
The change you are introducing is expecting all the Courses that are being inserted to be 'Available'. The tests that are failing are for the same. Do a search for 'Filler<Course>' in your solution, verify each one of them. All the filler methods should set the status to 'Available' as you have done in this PR.

**Comment by arafat-pro** [comment]
@ShriHumrudha Sincere thanks for your suggestion! Your tips worked like a charm, I guess from the above all check passed green check!
would you please suggest to me, how can I find such internal relations among various models?

**Comment by arafat-pro** [comment]
Sincere thanks to @hassanhabib for opening this opportunity to us and @ShriHumrudha for guiding me! with this marge my gitfyle score to 10 which means a lot to me!

**Pull request merged**
