### PR TITLE
CODE RUB: SEPERATE LOGIC TEST FOR DELETE OPERATION - Teachers

### PR DESCRIPTION
**Pull request by tharanisantosh**

### CODE REVIEW

**Review by ShriHumrudha — CHANGES_REQUESTED** [review]
Got conflicts

**Comment by tharanisantosh** [comment]
> 

Comment Resolved

**Review by ShriHumrudha — CHANGES_REQUESTED** [review]
Got conflicts

**Comment by tharanisantosh** [comment]
> Got conflicts

Resolved Conflicts.

**Comment by ShriHumrudha** [comment]
@tharanisantosh Got conflicts here

**Comment by ShriHumrudha** [comment]
Beyond the 3 day window.

**Review by ShriHumrudha — APPROVED** [review]

**Pull request merged**
