### PR TITLE
StudentSemesterCourse AcceptanceTests

### PR DESCRIPTION
**Pull request by tajwal**

### CODE REVIEW

**Comment by hassanhabib** [comment]
@tajwal  all PRs has been merged, make sure your acceptance tests are passing.

**Comment by tajwal** [comment]
> @tajwal all PRs has been merged, make sure your acceptance tests are passing.

Mr. @hassanhabib the all acceptance tests passed.

**Comment by hassanhabib** [comment]
@tajwal please merge with master

**Comment by tajwal** [comment]
> @tajwal please merge with master

Mr. @hassanhabib conflict is resolved and merged to master.

**Comment by hassanhabib** [comment]
thn

> > @tajwal please merge with master
> 
> Mr. @hassanhabib conflict is resolved and merged to master.

Thanks @tajwal 
@viralpandya  can you check this PR please?

**Pull request merged**
