### PR TITLE
CODE RUB: Corrected Validation exception for Modify

### PR DESCRIPTION
**Pull request by rcruzfreelance**
Closes #[571](https://github.com/hassanhabib/OtripleS/issues/571)

### CODE REVIEW

**Comment by ShriHumrudha** [comment]
I am thinking out loud if we want to keep the data arranging explicit in the test for the storytelling.

**Comment by hassanhabib** [comment]
> I am thinking out loud if we want to keep the data arranging explicit in the test for the storytelling.

@ShriHumrudha we can also expose an input parameter for `dates` - either way is okay.

**Comment by mtoncic** [comment]
> > I am thinking out loud if we want to keep the data arranging explicit in the test for the storytelling.
> 
> @ShriHumrudha we can also expose an input parameter for `dates` - either way is okay.

Fill like free to jump since I created an issue.
In the proposed solution there is a version:
```csharp
  DateTimeOffset createdAndUpdatedDate = DateTimeOffset.UtcNow;
  Student randomStudent= CreateRandomStudent(dates: createdAndUpdatedDate);
  Student invalidStudent = randomStudent;
```

I think that this would be the right match.

**Comment by hassanhabib** [comment]
> > > I am thinking out loud if we want to keep the data arranging explicit in the test for the storytelling.
> > 
> > 
> > @ShriHumrudha we can also expose an input parameter for `dates` - either way is okay.
> 
> Fill like free to jump since I created an issue. In the proposed solution there is a version:
> 
> ```cs
>   DateTimeOffset createdAndUpdatedDate = DateTimeOffset.UtcNow;
>   Student randomStudent= CreateRandomStudent(dates: createdAndUpdatedDate);
>   Student invalidStudent = randomStudent;
> ```
> 
> I think that this would be the right match.

@mtoncic that's a bad version. The dates here are generated from the datetime instead of random. We should randomize instead.

**Comment by hassanhabib** [comment]
Closing this due to inactivity

**Pull request closed without merging**
