### PR TITLE
CODE RUB: Remove Storage Validations from Calendar Entries Retrieve All

### PR DESCRIPTION
**Pull request by arafat-pro**

### CODE REVIEW

**Comment by hassanhabib** [comment]
@arafat-pro make sure you close the related issue

**Comment by arafat-pro** [comment]
> @arafat-pro make sure you close the related issue

@hassanhabib I can not see the Close button enabled in my interface to close this issue #641 
I don't know why, maybe I am creating PR from external being a non-team member of the OtripleS Project!
I am very new to git!
I seek your help in this regard!

**Comment by arafat-pro** [comment]
Closes #641

**Comment by hassanhabib** [comment]
> > @arafat-pro make sure you close the related issue
> 
> @hassanhabib I can not see the Close button enabled in my interface to close this issue #641 I don't know why, maybe I am creating PR from external being a non-team member of the OtripleS Project! I am very new to git! I seek your help in this regard!

No worries I closed it @arafat-pro

**Pull request merged**
