### PR TITLE
Muhammad Kasimov

### LINKED ISSUE #1968: CODE RUB: Rule & Parameter Should Be @ The Same Level
https://github.com/hassanhabib/OtripleS/blob/c259316151682656a16e657368d83dd3d122ba15/OtripleS.Web.Api/Services/Foundations/Students/StudentService.Validations.cs#L33

@moisesjgomez

### PR DESCRIPTION
**Pull request by MuhammadKasimov**
closed #1968 issue

### CODE REVIEW

**Comment by ElbekDeveloper** [comment]
This PR has bad commit history. Please, look through my YouTube channel on how to do proper commits for The-Standard compliant projects

**Comment by MuhammadKasimov** [comment]
> This PR has bad commit history. Please, look through my YouTube channel on how to do proper commits for The-Standard compliant projects

can you send link to your channel

**Comment by ElbekDeveloper** [comment]
https://www.youtube.com/watch?v=heJ88wBxRCU

**Comment by ElbekDeveloper** [comment]
@MuhammadKasimov

**Pull request closed without merging**
