### PR TITLE
Created Foundation service grouping

### PR DESCRIPTION
**Pull request by viralpandya**

### CODE REVIEW

**Comment by hassanhabib** [comment]
@viralpandya  you probably don't want to categorize foundations on the models folder. because models can be shared between foundations, processing, orchestrations and many other categories of services.
But I highly recommend it for services for sure.

**Comment by viralpandya** [comment]
We need for model as well as for every service we will have exception handling too and we need them in respective folders of every service. Let me know, i can revert back models to root folder. But still there will be no separation of folders in foundation

**Comment by hassanhabib** [comment]
> We need for model as well as for every service we will have exception handling too and we need them in respective folders of every service. Let me know, i can revert back models to root folder. But still there will be no separation of folders in foundation


@viralpandya models are shared across services of different categories - let's keep them in the open without categorization. Otherwise you will need to create two models with the exact same name in two different folders plus the mapping. Not a good idea.

**Comment by viralpandya** [comment]
Done changes.

**Pull request merged**
