### PR TITLE
I changed TeacherContacts.cs to TeacherContact.cs

### PR DESCRIPTION
**Pull request by Rashidovicc**

### CODE REVIEW

**Comment by Spectralgo** [comment]
Thanks :) I have some recommendations for you.

@Rashidovicc the pull request and the commit should be named:
CODE RUB: Rename TeacherContacts to TeacherContact 

You also have to create a new git branch instead of just pushing to the master branch. Look at other pull request and how they name their branch and commits. It has respect the same standard.

If you not sure of what I'm talking about, try to look at  Hassan's playlist sofee project. Follow along to learn a bit more of the standard.
 https://youtube.com/playlist?list=PLan3SCnsISTQ63o4HFkIw0YcEcOlwqt53

**Comment by Rashidovicc** [comment]
@Spectralgo Thanks for your feedback:) I will do this process as you said.

**Comment by Rashidovicc** [comment]
@Spectralgo  Thanks for your feedback:) I will do this process as you said.

**Comment by Rashidovicc** [comment]
@Spectralgo Can I close the PK to make it different?

**Comment by Spectralgo** [comment]
I'm really busy those days I'm packing all my stuff, I don't even have a desk anymore. I need to put everything on a cargo boat tomorrow. So I can't help you much more than that today. Have fun 😊

**Comment by Rashidovicc** [comment]
OK thanks you

**Pull request closed without merging**
