### PR TITLE
CODE RUB: Reaplce default with Guids to Guid.Empty

### PR DESCRIPTION
**Pull request by nedataghiparast**

### CODE REVIEW

**Review by ShriHumrudha — CHANGES_REQUESTED** [review]
Build failed, fix the errors

**Comment by nedataghiparast** [comment]
fixed the errors and send that again could you please check it.
Thank you.

**Comment by ShriHumrudha** [comment]
@nedataghiparast There are conflicts now.

**Comment by ShriHumrudha** [comment]
Beyond the 3 day window.

**Pull request closed without merging**
