### PR TITLE
Users controller

### PR DESCRIPTION
**Pull request by eriadhami**

### CODE REVIEW

**Comment by hassanhabib** [comment]
@eriadhami what happened to this PR?

**Comment by eriadhami** [comment]
> @eriadhami what happened to this PR?

Sorry i have closed by mistake

**Comment by hassanhabib** [comment]
> > @eriadhami what happened to this PR?
> 
> Sorry i have closed by mistake

@eriadhami  no worries - hold tight trying to revert a previous PR that's causing issues.

**Comment by hassanhabib** [comment]
> > > @eriadhami what happened to this PR?
> > 
> > 
> > Sorry i have closed by mistake
> 
> @eriadhami no worries - hold tight trying to revert a previous PR that's causing issues.

@eriadhami  looks like you're having some build issues, please address.

**Comment by eriadhami** [comment]
> > > > @eriadhami what happened to this PR?
> > > 
> > > 
> > > Sorry i have closed by mistake
> > 
> > 
> > @eriadhami no worries - hold tight trying to revert a previous PR that's causing issues.
> 
> @eriadhami looks like you're having some build issues, please address.

@hassanhabib I do not know what happened but now it passed. I just did a re-run check and it passed without errors.

**Pull request merged**
