### PR TITLE
Add Assignment controller

### PR DESCRIPTION
**Pull request by Mohamad-ali-8**

### CODE REVIEW

**Comment by hassanhabib** [comment]
@Mohamad-ali-8 looks like you got some build issues.

**Comment by hassanhabib** [comment]
All endpoints in assignments controller has been implemented and ran against acceptance tests, I appreciate your effort.

**Comment by Mohamad-ali-8** [comment]
thanks @hassanhabib, had to rush this one. We are entering a stage 4 lockdown in Melbourne Australia so had few things to do.

**Comment by hassanhabib** [comment]
> thanks @hassanhabib, had to rush this one. We are entering a stage 4 lockdown in Melbourne Australia so had few things to do.  

No worries brother - stay safe <3

**Pull request closed without merging**
